services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
            target: backend
            args:
                COMPOSER_NO_DEV: 0
        environment:
            APP_ENV: "dev"
            DATABASE_URL: "mysql://root:mysql@mysql/sylius_%kernel.environment%?charset=utf8mb4"
#            DATABASE_URL: "pgsql://root:postgres@postgres/sylius_%kernel.environment%?charset=utf8" # When using postgres
            PHP_DATE_TIMEZONE: "Europe/Warsaw"
            PHP_XDEBUG_IDEKEY: "PHPSTORM"
            MAILER_URL: "smtp://mailhog:1025"
        volumes:
            - ./:/app/
        ports:
            - ${APP_PORT:-80}:80
        depends_on:
            - mysql
            - postgres
    
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
            target: frontend
        volumes:
            - ./:/app/

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: mysql
        ports:
            - ${MYSQL_PORT:-3306}:3306
    
    postgres:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: postgres
        ports:
            - ${POSTGRES_PORT:-5432}:5432

    mailhog:
        image: mailhog/mailhog
        platform: linux/amd64
        ports:
            - ${MAILHOG_PORT:-8025}:8025 # UI

    blackfire:
        image: blackfire/blackfire:2
        environment:
            BLACKFIRE_LOG_LEVEL: 4
            BLACKFIRE_SERVER_ID: ~
            BLACKFIRE_SERVER_TOKEN: ~
            BLACKFIRE_CLIENT_ID: ~
            BLACKFIRE_CLIENT_TOKEN: ~
            BLACKFIRE_DISABLE_LEGACY_PORT: 1
        ports:
            - ${BLACKFIRE_PORT:-8307}:8307
