name: Build Docker Image

on:
    workflow_dispatch: ~
    push:
        branches-ignore:
            - 'dependabot/**'
        paths-ignore:
            - "*.md"
    pull_request:
        paths-ignore:
            - "*.md"

jobs:
    docker-build-image:
        name: Build Docker Image
        env:
            DOCKER_BUILDKIT: 1 # Requires Latest Buildx in docker CLI
        
        runs-on: ubuntu-latest
        steps:
            -
                name: Set Up QEMU
                uses: docker/setup-qemu-action@v2
            -
                name: Set Up Docker Buildx
                uses: docker/setup-buildx-action@v2
            -
                name: Build Image
                uses: docker/build-push-action@v4
                with:
                    push: false
                    platforms: linux/amd64,linux/arm64
                    cache-from: type=gha
                    cache-to: type=gha
                    load: false
